### ISSUE TITLE
Error while updating entity

### ISSUE THREAD

**Issue by rishikunnath2747** [cap-java/cds-feature-attachments#189]
I am part of the team that is developing the [SDM plugin](https://github.com/cap-java/sdm). We are facing an issue when we are updating an entity. Basically the following scenario.

1. First we create a new entity, and add attachments to it. The attachments are saved into SDM while uploading. The on clicking save, the entity is saved.
2. Now we try to edit the entity and add additional attachments to it. The attachments are saved into SDM while uploading like the previous step without any problems. 
3. However now when we try to save the entity, it throws this error

`Invalid CQN: Element 'DRAFT_READONLY_CONTEXT.contentId' does not exist in entity 'AdminService.Books.attachments'`

After we complete the process of saving the attachment in SDM, we execute the following code which is in the _createAttachment_ method which we have implemented in the _SDMAttachmentsServiceHandler_.

```
context.setIsInternalStored(true);
context.setContentId(contentId);
context.setCompleted();
```

Is there anything else we are supposed to set in the context to avoid getting this error?

**Comment by yashmeet29** [comment]
Hi @beckermarc @adamandre79  @BraunMatthias,
This is blocking development of SDM plugin. Can someone please look into this issue.

Regards,
Yashmeet

**Comment by adamandre79** [comment]
Hello colleagues,

I found the root cause of the problem:

You added an annotation `@Core.Immutable` to the `content` field of the attachment model. With this content field is removed from the data during update for the attachment which was created first and so the error occurs.

I tested it without this annotation and it works.
During testing I found some other annotations, where I'm not sure, if they can cause trouble on other places like: `@odata.draft.skip`.

To avoid such problem in the future, please do not copy the model which is defined in the attachment plugin.
If additional things are needed you can enhance the model, but please do not add annotations which are not needed for your development.
The attachment plugin expects fields and annotations as they are defined in the attachment plugin data model.

On additional remark to the properties you set in the context during the create process: please only set fields you need for your processing, so please do not set the following property:

```
context.setIsInternalStored(true);
```
 
As described in the [design](https://github.com/cap-java/cds-feature-attachments/blob/main/doc/Design.md#internal-stored) which was already shared with you, this property only needs to be set if the attachment shall be stored in the database and not in an external system.

Regards
André
